// Dataset compacto de emojis con palabras clave (español) para el buscador del chat.
// No es exhaustivo pero cubre los más usados en un equipo. Sin dependencias externas.
export type Emoji = { c: string; k: string };

export const EMOJI_LIST: Emoji[] = [
  // Reacciones rápidas (aparecen primero)
  { c: "👍", k: "like bien pulgar arriba ok si aprobado" },
  { c: "❤️", k: "corazon amor rojo like" },
  { c: "🎉", k: "fiesta celebrar tada confeti logro" },
  { c: "🔥", k: "fuego fire genial increible" },
  { c: "😂", k: "risa lol jaja llorar chistoso" },
  { c: "👀", k: "ojos mirar viendo atento" },
  { c: "🙌", k: "manos arriba yay celebrar" },
  { c: "💯", k: "cien perfecto total 100" },
  { c: "🚀", k: "cohete rapido lanzar despegar" },
  { c: "🙏", k: "gracias porfa rezar manos" },
  { c: "✅", k: "check hecho listo ok completado" },
  { c: "💪", k: "fuerza musculo animo poder" },
  { c: "⚡", k: "rayo energia rapido" },
  { c: "😮", k: "sorpresa wow asombro" },
  { c: "🫶", k: "corazon manos amor cariño" },
  { c: "👏", k: "aplauso bravo felicidades" },
  // Caras
  { c: "😀", k: "sonrisa feliz cara" },
  { c: "😁", k: "sonrisa dientes feliz" },
  { c: "😅", k: "risa nervios sudor" },
  { c: "🤣", k: "risa piso jaja" },
  { c: "🙂", k: "sonrisa leve" },
  { c: "😊", k: "feliz sonrojo contento" },
  { c: "😇", k: "angel inocente" },
  { c: "😍", k: "amor ojos corazon enamorado" },
  { c: "😘", k: "beso amor" },
  { c: "😎", k: "cool lentes genial" },
  { c: "🤩", k: "estrellas wow admiracion" },
  { c: "🤔", k: "pensar duda mmm" },
  { c: "🤨", k: "ceja duda sospecha" },
  { c: "😐", k: "neutral serio" },
  { c: "😴", k: "dormir sueño cansado" },
  { c: "😭", k: "llorar triste llanto" },
  { c: "😤", k: "enojo frustracion vapor" },
  { c: "😡", k: "enojo furia rojo molesto" },
  { c: "🥳", k: "fiesta cumpleaños celebrar" },
  { c: "🥺", k: "suplica ojos porfa tierno" },
  { c: "😬", k: "incomodo nervioso mueca" },
  { c: "🤗", k: "abrazo carino" },
  { c: "🤯", k: "explota mente wow shock" },
  { c: "😱", k: "grito miedo shock" },
  { c: "🥴", k: "mareado ebrio confuso" },
  { c: "🤒", k: "enfermo termometro" },
  { c: "🤝", k: "acuerdo trato manos deal" },
  // Gestos y personas
  { c: "👋", k: "hola adios saludo mano" },
  { c: "🤙", k: "llamame shaka" },
  { c: "✌️", k: "paz victoria dedos" },
  { c: "🤞", k: "suerte dedos cruzados" },
  { c: "👌", k: "ok perfecto dedos" },
  { c: "🤟", k: "te amo rock mano" },
  { c: "👇", k: "abajo señalar" },
  { c: "👆", k: "arriba señalar" },
  { c: "👉", k: "derecha señalar" },
  { c: "🫡", k: "saludo militar respeto entendido" },
  { c: "🧠", k: "cerebro mente idea inteligente" },
  { c: "👑", k: "corona rey reina lider" },
  // Corazones y símbolos
  { c: "🧡", k: "corazon naranja" },
  { c: "💛", k: "corazon amarillo" },
  { c: "💚", k: "corazon verde" },
  { c: "💙", k: "corazon azul" },
  { c: "💜", k: "corazon morado" },
  { c: "🖤", k: "corazon negro" },
  { c: "💔", k: "corazon roto triste" },
  { c: "✨", k: "brillos magia estrellas genial" },
  { c: "⭐", k: "estrella favorito" },
  { c: "🌟", k: "estrella brillo destacar" },
  { c: "💥", k: "explosion boom impacto" },
  { c: "💫", k: "mareo estrellas" },
  { c: "❗", k: "importante exclamacion atencion" },
  { c: "❓", k: "pregunta duda" },
  { c: "✔️", k: "check listo" },
  { c: "❌", k: "error mal no cruz" },
  { c: "⚠️", k: "advertencia cuidado alerta" },
  { c: "🚫", k: "prohibido no alto" },
  // Trabajo / objetos
  { c: "💡", k: "idea foco bombilla" },
  { c: "📌", k: "pin fijar chincheta" },
  { c: "📎", k: "clip adjuntar" },
  { c: "📝", k: "nota escribir apunte tarea" },
  { c: "✏️", k: "lapiz editar escribir" },
  { c: "📅", k: "calendario fecha agenda" },
  { c: "⏰", k: "reloj alarma tiempo hora" },
  { c: "⏳", k: "reloj arena esperar tiempo" },
  { c: "📈", k: "grafica sube crecimiento" },
  { c: "📉", k: "grafica baja caida" },
  { c: "📊", k: "grafica barras datos" },
  { c: "💼", k: "trabajo maletin negocio" },
  { c: "💰", k: "dinero bolsa plata" },
  { c: "💵", k: "dinero billete dolar" },
  { c: "🎯", k: "meta objetivo diana target" },
  { c: "🏆", k: "trofeo ganar premio" },
  { c: "🥇", k: "oro primero medalla" },
  { c: "📱", k: "celular telefono movil" },
  { c: "💻", k: "laptop computadora trabajo" },
  { c: "⌨️", k: "teclado escribir" },
  { c: "📢", k: "anuncio megafono aviso" },
  { c: "🔔", k: "campana notificacion aviso" },
  { c: "🔒", k: "candado seguro privado" },
  { c: "🔑", k: "llave acceso" },
  { c: "🔗", k: "enlace link cadena" },
  { c: "☕", k: "cafe descanso" },
  { c: "🍕", k: "pizza comida" },
  { c: "🍺", k: "cerveza chela festejo" },
  { c: "🎂", k: "pastel cumpleaños" },
  { c: "🎁", k: "regalo sorpresa" },
  // Naturaleza / varios
  { c: "🌈", k: "arcoiris color" },
  { c: "☀️", k: "sol dia clima" },
  { c: "🌙", k: "luna noche" },
  { c: "🌊", k: "ola mar agua" },
  { c: "🐝", k: "abeja ocupado" },
  { c: "🦄", k: "unicornio magia especial" },
  { c: "🐢", k: "tortuga lento" },
  { c: "🙈", k: "mono no veo pena" },
  { c: "💩", k: "caca popo broma" },
  { c: "🤖", k: "robot ia bot" },
  { c: "👻", k: "fantasma boo" },
  { c: "🫠", k: "derretir calor incomodo" },
];
